### ISSUE TITLE
Water Pump

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/LDJam50#27]

**Comment by aagusindigo** [comment]
![image.png](https://zube.io/files/enigmadragons/cdd1da39a2b44f0739410ae8fe99e2ae-image.png) 
you mean something like this?

**Comment by SilasReinagel** [comment]
@aagusindigo It can be any water source you like.

Maybe a farm water pump. Maybe a fountain. Totally up to you.
